# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        MainWindow.setMinimumSize(QtCore.QSize(750, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ColourButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ColourButton.setMinimumSize(QtCore.QSize(0, 40))
        self.ColourButton.setObjectName("ColourButton")
        self.verticalLayout.addWidget(self.ColourButton)
        self.CategoriesButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CategoriesButton.setMinimumSize(QtCore.QSize(0, 40))
        self.CategoriesButton.setObjectName("CategoriesButton")
        self.verticalLayout.addWidget(self.CategoriesButton)
        self.TagButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.TagButton.setMinimumSize(QtCore.QSize(0, 40))
        self.TagButton.setObjectName("TagButton")
        self.verticalLayout.addWidget(self.TagButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.SystemButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SystemButton.setMinimumSize(QtCore.QSize(0, 40))
        self.SystemButton.setCheckable(False)
        self.SystemButton.setChecked(False)
        self.SystemButton.setObjectName("SystemButton")
        self.verticalLayout.addWidget(self.SystemButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(208, 20, 531, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.RightMenu = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.RightMenu.setContentsMargins(0, 0, 0, 0)
        self.RightMenu.setObjectName("RightMenu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ColourButton.setText(_translate("MainWindow", "Colours"))
        self.CategoriesButton.setText(_translate("MainWindow", "Categories"))
        self.TagButton.setText(_translate("MainWindow", "Tags"))
        self.SystemButton.setText(_translate("MainWindow", "System"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
